version: '3'
services:
  node-app:
    container_name: node-app
    image: node
    user: root
    command: ["/bin/bash","-lc","npm i && npm start"]
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - ./.env.docker:/home/node/app/.env
    networks:
      - node-network
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance
    networks:
      - node-network
volumes:
  dbdata:
networks:
  node-network:
    driver: bridge