
const joi = require('joi');
const {
  options, isCountOnly, include, select 
} = require('./commonFilterValidation');
    
exports.schemaKeys = joi.object({
  owner_id: joi.number().integer().allow(0),
  user_id: joi.number().integer().allow(0),
  number: joi.string().allow(null).allow(''),
  ar_id: joi.number().integer().allow(0),
  status: joi.number().integer().allow(0),
  amount: joi.number().allow(0),
  amount_paid: joi.number().allow(0),
  date: joi.any(),
  due_date: joi.any(),
  additional_info: joi.string().allow(null).allow(''),
  payment_id: joi.number().integer().allow(0),
  discount_id: joi.number().integer().allow(0),
  created_at: joi.date().options({ convert: true }).allow(null).allow(''),
  with: joi.string().allow(null).allow(''),
  zone: joi.string().allow(null).allow(''),
  created_by: joi.number().integer().allow(0),
  updated_at: joi.date().options({ convert: true }).allow(null).allow(''),
  updated_by: joi.number().integer().allow(0),
  deleted_at: joi.date().options({ convert: true }).allow(null).allow(''),
  deleted_by: joi.number().integer().allow(0),
  period_id: joi.number().integer().allow(0),
  class_program_id: joi.number().integer().allow(0),
  class_level_id: joi.number().integer().allow(0),
  class_specialization_id: joi.number().integer().allow(0),
  male: joi.boolean(),
  recurring_type: joi.number().integer().allow(0),
  recurring_period: joi.number().integer().allow(0),
  installment: joi.number().integer().allow(0),
  mutation: joi.boolean(),
  boarding: joi.boolean(),
  admission_line_id: joi.number().integer().allow(0),
  admission_batch_id: joi.number().integer().allow(0),
  isActive: joi.boolean(),
  isDeleted: joi.boolean()
}).unknown(true);
exports.updateSchemaKeys = joi.object({
  owner_id: joi.number().integer().allow(0),
  user_id: joi.number().integer().allow(0),
  number: joi.string().allow(null).allow(''),
  ar_id: joi.number().integer().allow(0),
  status: joi.number().integer().allow(0),
  amount: joi.number().allow(0),
  amount_paid: joi.number().allow(0),
  date: joi.any(),
  due_date: joi.any(),
  additional_info: joi.string().allow(null).allow(''),
  payment_id: joi.number().integer().allow(0),
  discount_id: joi.number().integer().allow(0),
  created_at: joi.date().options({ convert: true }).allow(null).allow(''),
  with: joi.string().allow(null).allow(''),
  zone: joi.string().allow(null).allow(''),
  created_by: joi.number().integer().allow(0),
  updated_at: joi.date().options({ convert: true }).allow(null).allow(''),
  updated_by: joi.number().integer().allow(0),
  deleted_at: joi.date().options({ convert: true }).allow(null).allow(''),
  deleted_by: joi.number().integer().allow(0),
  period_id: joi.number().integer().allow(0),
  class_program_id: joi.number().integer().allow(0),
  class_level_id: joi.number().integer().allow(0),
  class_specialization_id: joi.number().integer().allow(0),
  male: joi.boolean(),
  recurring_type: joi.number().integer().allow(0),
  recurring_period: joi.number().integer().allow(0),
  installment: joi.number().integer().allow(0),
  mutation: joi.boolean(),
  boarding: joi.boolean(),
  admission_line_id: joi.number().integer().allow(0),
  admission_batch_id: joi.number().integer().allow(0),
  isActive: joi.boolean(),
  isDeleted: joi.boolean(),
  id: joi.number().integer()
}).unknown(true);
let keys = ['query', 'where'];
exports.findFilterKeys = joi.object({
  options: options,
  ...Object.fromEntries(
    keys.map(key => [key, joi.object({
      owner_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      user_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      number: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
      ar_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      status: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      amount: joi.alternatives().try(joi.array().items(),joi.number(),joi.object()),
      amount_paid: joi.alternatives().try(joi.array().items(),joi.number(),joi.object()),
      date: joi.alternatives().try(joi.array().items(),joi.any(),joi.object()),
      due_date: joi.alternatives().try(joi.array().items(),joi.any(),joi.object()),
      additional_info: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
      payment_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      discount_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      created_at: joi.alternatives().try(joi.array().items(),joi.date().options({ convert: true }),joi.object()),
      with: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
      zone: joi.alternatives().try(joi.array().items(),joi.string(),joi.object()),
      created_by: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      updated_at: joi.alternatives().try(joi.array().items(),joi.date().options({ convert: true }),joi.object()),
      updated_by: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      deleted_at: joi.alternatives().try(joi.array().items(),joi.date().options({ convert: true }),joi.object()),
      deleted_by: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      period_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      class_program_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      class_level_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      class_specialization_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      male: joi.alternatives().try(joi.array().items(),joi.boolean(),joi.object()),
      recurring_type: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      recurring_period: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      installment: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      mutation: joi.alternatives().try(joi.array().items(),joi.boolean(),joi.object()),
      boarding: joi.alternatives().try(joi.array().items(),joi.boolean(),joi.object()),
      admission_line_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      admission_batch_id: joi.alternatives().try(joi.array().items(),joi.number().integer(),joi.object()),
      isActive: joi.alternatives().try(joi.array().items(),joi.boolean(),joi.object()),
      isDeleted: joi.alternatives().try(joi.array().items(),joi.boolean(),joi.object()),
      id: joi.any(),
      createdAt: joi.any(),
      updatedAt: joi.any()
    }).unknown(true),])
  ),
  isCountOnly: isCountOnly,
  include: joi.array().items(include),
  select: select
    
}).unknown(true);
